channels:
  - conda-forge
dependencies:
  - python=3.7
  - sat-search
  - dask>=2.23.0
  - numpy
  - xarray
  - geopandas
  - intake
  - intake-stac
  - matplotlib
  - rasterio
  - requests
  - geoviews
  - fsspec
  - s3fs
  - zarr