name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - coiled
  - sat-search
  - dask
  - xarray
  - geopandas
  - intake
  - intake-stac
  - matplotlib
  - rasterio
  - requests
  - geoviews