
name: Build environments

on: ["push", "pull_request"]
  # push:
  #   branches: master
  # pull_request:
  #   branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DASK_COILED__SERVER: https://beta.coiled.io
      DASK_COILED__TOKEN: ${{ secrets.DASK_COILED__TOKEN }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Coiled
        run: python -m pip install coiled

      - name: Build software environments
        run: python build_environments.py